version: '3'
services:
  db:
    image: mysql:5-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Jogos

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: Jogos

  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - api
