version: '3'
services:
  db:
    image: mysql:5-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Jogos
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: Jogos

volumes:
  db_data:
